name: CI

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
  workflow_dispatch:

jobs:
  test:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git log -25
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npx contentlayer build
      - run: ls node_modules/next/image-types
      - run: ls public/images
      - run: npm run check
